### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [Thesola10/zsh-ubuntu-ish#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by Thesola10** [comment]
I have added a screenshot. Is it suitable for your needs?

**Comment by Thesola10** [comment]
Also, may I request that my theme be listed as `ubuntu-ish`, as per the theme filename, instead of the repository name (`zsh-ubuntu-ish`)?

**Comment by unixorn** [comment]
Yes, I strip off leading  `zsh-` and similar prefixes.

Could you also add a license file?

**Comment by Thesola10** [comment]
I have updated the repository with a CC0 license. (Yes, that means it's in the public domain now)
